services:
  # Backend API service
  - type: web
    name: meeting-summarizer
    runtime: docker
    plan: pro
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production