services:
  # Backend API service
  - type: web
    name: meeting-summarizer
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y ffmpeg

      # Install Python dependencies
      pip install --no-cache-dir -r requirements.txt

      # Install Node.js LTS
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs

      echo "Node and npm versions:"
      node --version
      npm --version

      # Build frontend
      echo "Building frontend..."
      cd frontend
      
      # Debug frontend directory
      echo "Frontend directory contents:"
      ls -la
      
      # Install dependencies and build
      npm ci
      GENERATE_SOURCEMAP=false npm run build
      
      echo "Build output:"
      ls -la build/
      
      # Copy to static directory
      cd ..
      rm -rf static
      cp -r frontend/build static
      
      echo "Final static directory:"
      ls -la static/

    startCommand: |
      echo "Starting server..."
      echo "Current directory structure:"
      pwd
      ls -la
      echo "Static directory contents:"
      ls -la static/
      
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        value: test_openai_key
      - key: REACT_APP_API_URL
        value: https://meeting-summarizer.onrender.com
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
    plan: pro
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      memory: 2048Mi