services:
  # Backend API service
  - type: web
    name: meeting-summarizer
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y ffmpeg

      # Install Python dependencies with memory optimization
      pip install --no-cache-dir -r requirements.txt

      # Install Node.js and build frontend with reduced memory
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      cd frontend && NODE_OPTIONS=--max_old_space_size=512 npm install && npm run build
      cd ..
    staticPublishPath: ./frontend/build
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        value: test_openai_key
      - key: REACT_APP_API_URL
        value: https://meeting-summarizer.onrender.com
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      memory: 2048Mi

  # Frontend service
  - type: web
    name: meeting-summarizer-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://meeting-summarizer-api.onrender.com 