services:
  # Backend API service
  - type: web
    name: meeting-summarizer
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y ffmpeg

      # Install Python dependencies
      pip install --no-cache-dir -r requirements.txt

      # Debug - show current directory
      echo "Current directory before frontend build:"
      pwd
      ls -la

      # Install Node.js and build frontend
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs

      # Debug - show Node and npm versions
      echo "Node version:"
      node --version
      echo "npm version:"
      npm --version

      # Build frontend with detailed output
      echo "Building frontend..."
      cd frontend
      echo "Installing dependencies..."
      CI=false npm install --verbose
      echo "Running build..."
      CI=false npm run build --verbose
      cd ..

      # Create static directory and copy files
      echo "Creating static directory..."
      mkdir -p /app/static
      echo "Copying build files..."
      cp -rv frontend/build/* /app/static/
      
      # Verify files
      echo "Checking static directory contents:"
      ls -la /app/static/

    startCommand: |
      # Final verification
      echo "Final directory structure:"
      pwd
      ls -la
      echo "Static directory contents:"
      ls -la /app/static/
      
      # Start server
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        value: test_openai_key
      - key: REACT_APP_API_URL
        value: https://meeting-summarizer.onrender.com
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      memory: 2048Mi 