services:
  # Backend API service
  - type: web
    name: meeting-summarizer
    runtime: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y ffmpeg
      
      # Install Python dependencies
      pip install -r requirements.txt
      
      # Install Node and build frontend
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      cd frontend
      npm install
      npm run build
      cd ..
      
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: OPENAI_API_KEY
        sync: false
    plan: pro
    scaling:
      minInstances: 1
      maxInstances: 1