services:
  # Backend API service
  - type: web
    name: meeting-summarizer
    runtime: python
    buildCommand: |
      # Install Node.js first
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      
      # Build frontend
      cd frontend && npm install && npm run build && cd ..
      
      # Then install Python dependencies
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
    plan: pro
    scaling:
      minInstances: 1
      maxInstances: 1