services:
  # Backend API service
  - type: web
    name: meeting-summarizer
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y ffmpeg

      # Install Python dependencies
      pip install --no-cache-dir -r requirements.txt

      # Debug - show current directory
      echo "Current directory before frontend build:"
      pwd

      # Install Node.js and build frontend
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs

      # Debug - show Node and npm versions
      node --version
      npm --version

      # Build frontend
      cd frontend
      npm install
      npm run build
      cd ..

      # Debug - verify build output
      echo "Checking if frontend/build exists:"
      ls -la frontend/build/
      echo "Checking if frontend/build/static exists:"
      ls -la frontend/build/static/
      echo "Checking if frontend/build/index.html exists:"
      cat frontend/build/index.html

      # Copy build files to a location FastAPI can serve
      mkdir -p static
      cp -r frontend/build/* static/

    startCommand: |
      # Debug - verify files before starting
      echo "Checking static files before starting server:"
      ls -la static/
      
      # Start the server
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        value: test_openai_key
      - key: REACT_APP_API_URL
        value: https://meeting-summarizer.onrender.com
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      memory: 2048Mi 