services:
  # Backend API service
  - type: web
    name: meeting-summarizer
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y ffmpeg

      # Install Python dependencies
      pip install --no-cache-dir -r requirements.txt

      # Install Node.js LTS
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs

      echo "Node and npm versions:"
      node --version
      npm --version

      # Build frontend
      echo "Building frontend..."
      cd frontend
      echo "Frontend directory contents:"
      ls -la
      
      # Clean install dependencies
      echo "Installing dependencies..."
      rm -rf node_modules package-lock.json
      npm install
      
      echo "Building React app..."
      npm run build
      
      echo "Build directory contents:"
      ls -la build/
      
      # Copy to static directory
      cd ..
      echo "Creating static directory..."
      mkdir -p static
      echo "Copying build files..."
      cp -r frontend/build/* static/
      echo "Copying static files..."
      mkdir -p static/static
      cp -r frontend/build/static/* static/static/
      
      echo "Final directory structure:"
      ls -la
      echo "Static directory contents:"
      ls -la static/
      echo "Static/static directory contents:"
      ls -la static/static/

    startCommand: |
      echo "Starting server..."
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      echo "Static directory contents:"
      ls -la static/
      
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        value: test_openai_key
      - key: REACT_APP_API_URL
        value: https://meeting-summarizer.onrender.com
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: GENERATE_SOURCEMAP
        value: false
    plan: pro
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      memory: 2048Mi