services:
  # Backend API service
  - type: web
    name: meeting-summarizer
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y ffmpeg

      # Install Python dependencies
      pip install --no-cache-dir -r requirements.txt

      # Install Node.js and build frontend
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      
      echo "Node.js version:"
      node --version
      echo "npm version:"
      npm --version
      
      echo "Building frontend..."
      cd frontend
      echo "Installing dependencies..."
      npm install
      echo "Running build..."
      npm run build || {
        echo "Build failed! Checking package.json:"
        cat package.json
        echo "Checking for build errors:"
        npm run build --verbose
        exit 1
      }
      cd ..

      echo "Checking build output:"
      ls -la frontend/build/
      echo "Checking index.html:"
      cat frontend/build/index.html || echo "index.html not found!"

    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        value: test_openai_key
      - key: REACT_APP_API_URL
        value: https://meeting-summarizer.onrender.com
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      memory: 2048Mi 